### ISSUE TITLE
Parsing a single CSV line without knowing the amount of columns or header names

### ISSUE THREAD

**Issue by marcobusemann** [vincentlaucsb/csv-parser#102]
Hey, 

first of all thanks for your great work on this library. 
Actually i am testing your library and trying different scenarios.
I got stuck with parsing a single CSV line. I don't know the amount of columns or the header names in advance. 

I tried the following:
```c++
      const auto format = csv::CSVFormat()
         .delimiter(',')
         .quote('\"');

      auto rows = csv::parse("\"234\n,345\",456", format);

      std::cout << "Cols: " << std::endl;
      const auto colNames = rows.get_col_names();
      for (const auto &colName : colNames)
         std::cout << "\""<< colName << "\"";
      if (colNames.size() > 0)
         std::cout << std::endl;

      std::cout << "Lines: " << std::endl;
      for (auto row : rows)
      {
         for (auto value : row)
            std::cout << "\"" << value.get<>() << "\" ";
         std::cout << std::endl;
      }
```

The result is:
```
Cols:
Lines:
"" "345" "456"
```

I think the first value of the line is interpreted as part of the header. 
I find no way to say that there is no header.
A combination of the following does not help here.
```
format
   .column_names(std::vector<std::string>())
   .variable_columns(csv::VariableColumnPolicy::KEEP)

....

Cols:
Lines:

"" "345" "456"
```

Has anyone an idea?

**Comment by vincentlaucsb** [comment]
Thanks for your post. To be honest, I don't think I've actually tested this case. Let me see what I can do.

**Comment by vincentlaucsb** [comment]
`CSVFormat` now has a `no_header()` method
