### ISSUE TITLE
Single column CSV cannot be parsed

### ISSUE THREAD

**Issue by f3rm4rf3r** [vincentlaucsb/csv-parser#105]
A single column CSV file will break the parser.

The following test makes the test suite fail:
```C++
TEST_CASE( "Single column CSV", "[read_singlecol_direct]" ) {
    auto rows = "A\r\n" // Header row
                "123\r\n"
                "1\r\n"
                "4"_csv;
   
    // Expected Results
    CSVRow row;
    rows.read_row(row);
    vector<string> first_row = {"123"};
    REQUIRE( vector<string>(row) == first_row );
}
```
CSVWriter doesn't seems to have a problem production such output but CSVReader seems to fail parsing it. 
I tried to dig into it but I don't have enough time to debug/patch it at the moment.

**Comment by vincentlaucsb** [comment]
This shouldn't happen. I think I know the reason, but I'm planning on replacing the internal data structures for representing rows to something more efficient anyways.

**Comment by grunk** [comment]
Hi,
any news on that matter ?
I have the same issue with one file among others which have only one column and i have to fallback to a manual parsing which is way uglier than the convinent loop that your parser offer.

**Comment by vincentlaucsb** [comment]
@grunk I'm working on a rewrite of a lot of the parser internals right now which will make the parser faster as well as fix this issue

**Comment by vincentlaucsb** [comment]
Fixed in the latest release
