### ISSUE TITLE
Getting Column Data Types with get_dtypes()

### ISSUE THREAD

**Issue by CleanHit** [vincentlaucsb/csv-parser#11]
I tried your example code for some file statistics here [csv::CSVStat Class Reference](https://vincentlaucsb.github.io/csv-parser/classcsv_1_1CSVStat.html#a881131249d111032b2da1ca81b71e96c). Here is a minimal example:

```
csv::CSVStat stats(csvFilePath);
auto colDataTypes = stats.get_dtypes();
auto colNames = stats.get_col_names();

// Doesn't work for colDataTypes but works for other defined statistics like max, min and so `on...`
for (int64_t it = 0; it < colNames.size(); it++){
    std::cout << colDataTypes[it] << std::endl;
}

// Doesn't work either
for (auto &type : colDataTypes){
    std::cout << type << std::endl;
}
```
How can I get the `colDataTypes` of each column printed out? If I understood it correctly that is what the `get_dtypes()`function suppose to do.

**Comment by vincentlaucsb** [comment]
Unlike the other `get_` functions which return vectors of numbers, `get_dtypes()` returns a vector of `std::unordered_map`s which counts the occurrences of each data type.

**Comment by CleanHit** [comment]
so I should be able to iterate and print it out with it, or?
```
std::unordered_map<std::string, csv::DataType >::iterator it = colDataTypes.begin();
while(it != colDataTypes.end())
{
    std::cout << it->first << " : " << it->second << std::endl;
    it++;
}
```

**Comment by CleanHit** [comment]
I got it working with:
```
std::cout << "Columns Data Types" << std::endl;
for (auto i = 0; i < colNames.size(); i++) 
{
    for (auto item : colDataTypes[i])
    {
        std::cout << colNames[item.first] << " : " << item.second << std::endl;
    }
}
```

**Comment by vincentlaucsb** [comment]
Call `csv::internals::type_name()` on the data type numbers, or write your own function which prints out the string representation.

**Comment by CleanHit** [comment]
Thanks, that did the trick.
