### ISSUE TITLE
Online documentation is currently unavailable

### ISSUE THREAD

**Issue by Dkapps** [vincentlaucsb/csv-parser#111]
Hello,

As implied in the title, the link in the README currently points to a 404 (which is a shame, I wanted to check how your library can be integrated in my project).

Regards,

**Comment by vincentlaucsb** [comment]
@Dkapps It should be back up (https://vincentlaucsb.github.io/csv-parser/html/index.html)

**Comment by eli-b** [comment]
The documentation seems to be down again. Should I open a separate issue?
