### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by belzebuu** [vincentlaucsb/csv-parser#116]
Thanks a lot for this nice library!
I am using it and I would like to be able to handle empty files. Currently, it seems that reading an empty file or a file with only the header causes the program to exit. Is it possible to return an exception so that I can catch it, instead? 
Thanks!
Marco

**Comment by vincentlaucsb** [comment]
Sorry for the late reply, but I've fixed this in the latest release. Thanks for your report and your kind words.

In the latest release you can do something like
```cpp
CSVReader reader("empty_file.csv")

for (auto& row: reader) {
   ...
}

if (reader.empty()) { // or reader.size() == 0
   std::cout << "File is empty" << std::endl;
}
```
