### ISSUE TITLE
Passing an input stream to the constructor of CSVReader

### ISSUE THREAD

**Issue by fakuivan** [vincentlaucsb/csv-parser#117]
Seems kinda odd for the ``CSVWriter`` to accept output streams but for the ``CSVReader`` to only accept file names. Is there any function for reading from input streams that maybe I'm not aware of?

**Comment by vincentlaucsb** [comment]
@fakuivan From the online documentation at http://vincela.com/csv/ (I just recently fixed the documentation link--you didn't miss anything) there are methods for reading in-memory strings.
