### ISSUE TITLE
CSVWriter::write_row not compatible with std::array

### ISSUE THREAD

**Issue by fakuivan** [vincentlaucsb/csv-parser#118]
The inclusion of the ``Allocator`` template parameter makes this incompatible with ``std::array``

**Comment by vincentlaucsb** [comment]
Hi @fakuivan. Previously `write_row` was restricted to just `std::vector<std::string>`, so thanks for bringing to my attention that it doesn't work with `std::array`.

**Comment by vincentlaucsb** [comment]
Fixed in #127
