### ISSUE TITLE
Row count returned by get_file_info is not correct

### ISSUE THREAD

**Issue by vvuros** [vincentlaucsb/csv-parser#119]
I have a csv file that contains a header row for 6 columns and one row of data.

I like to know how many rows are in the file by using following piece of code.
       csv::CSVFileInfo info =  csv::get_file_info(filepath.c_str());
       csv::RowCount row_count = info.n_rows;

info.n_rows returns 0. it should be 1.

It appears that the count is one less of the actual count. If I put 2 data rows into the file, n_rows returns 1. 
If I have just a header, it returns correctly 0.

It seems that the first data row is not included to the count.

**Comment by vincentlaucsb** [comment]
You are correct that the header row is not counted. I think I should have been more clear about it.

I'll leave this open until I come up with a clearer way for users to get the exact count they wanted.

**Comment by vvuros** [comment]
Thanks for your response.
Yes, it is ok that the header is not counted. My point was show that number of data rows is not counted correctly.

If I have a csv file like this:
    <header row>
    <data row 1>
    <data row 2>

The returned count is 1, it should be 2.

**Comment by vincentlaucsb** [comment]
I'm closing this for now since the parsing algorithm has been updated. If this issue still occurs then feel free to provide a file where rows are not counted correctly.
