### ISSUE TITLE
Documentation Link failure with possible website security observation

### ISSUE THREAD

**Issue by scottfurry** [vincentlaucsb/csv-parser#120]
Reading through project README file on github, a reference exists (see https://github.com/vincentlaucsb/csv-parser#documentation) for the user to click through to online documentation. Link directs browser to the page https://vincentlaucsb.github.io/csv-parser/html/ and results in a 404 error.

Thinking that just the directory structure could be the culprit, I shortened the url to just https://vincentlaucsb.github.io, i.e. cut out folder paths from the URL, only to be greeted by the text:
"DOES THIS WORK????", which suggests to me that the server root may be exposed.

Creating an issue for awareness.

**Comment by vincentlaucsb** [comment]
Hi, you can access the documentation at http://vincela.com/csv/.

The https://github.com/ URL was working for a while until it didn't. Not sure what happened there, but I've reverted to just hosting it on my personal site.
