### ISSUE TITLE
a situation the iterator will failed

### ISSUE THREAD

**Issue by alongL** [vincentlaucsb/csv-parser#121]
mediaproxy.csv content:  only have head , no content
```
dest,url


```

this code will failed for null  iterator.
``` 
      CSVReader reader("mediaproxy.csv");
	for (CSVRow& row : reader)  // this line error occours
	{
		for (CSVField& field : row) 
		{
    		     std::cout << field.get<>() << endl;
		}
	}
```

![sssssssssss](https://user-images.githubusercontent.com/5533883/91545147-4bb60980-e953-11ea-8c7c-6aa10d5b381d.png)

**Comment by vincentlaucsb** [comment]
Thanks for your report. I've fixed this in the latest release.
