### ISSUE TITLE
Cannot parse csv file where the delimiter is Non-ASCII code § (Win10 with VS2017)

### ISSUE THREAD

**Issue by ForrestFeng** [vincentlaucsb/csv-parser#123]
I have a CSV file with content as below

A§B§C§D§E§F
13§2019-01-25§nnn§Info§4716§aaa
14§2019-01-26§ppp§Info§4719§bbb

It is saved as utf-8 encoding

row.tojson() gives a result of {"13Â":"13Â","2019-01-25Â":"2019-01-25Â","nnnÂ":"pppÂ","InfoÂ":"InfoÂ","4716Â":"4719Â","aaa":"bbb"} where the Â is not expected.

This is because the 
CVSFormat.delimiter() canonly accept one char. 
'§' is not an ASCII char.
When encoded as utf-8 it becomes '\xC2\xA7' (check it [UTF-8 encoder/decoder](https://mothereff.in/utf-8#Foo%20%C2%A9%20bar%20%F0%9D%8C%86%20baz%20%E2%98%83%20qux) ) 

Could we support the Unicode delimiter like §，☃?

Thanks

**Comment by vincentlaucsb** [comment]
You could probably make a fork of the CSV parser that supports multi-byte delimiters but I don't really intend on doing that at the moment.
