### ISSUE TITLE
why DelimWriter constructor parameter is made as a reference?

### ISSUE THREAD

**Issue by tesla1060** [vincentlaucsb/csv-parser#128]
Hi, 
I understand this is because it has a private member as reference,

```
    private:
        OutputStream & out;
```

But design this way, will make below code's ofstream out of scope,

```
int main() {
    shared_ptr<csv::CSVWriter<std::ofstream>> writer;
    {
        ofstream fs("csv_writer_test.csv");
        writer = make_shared<csv::CSVWriter<std::ofstream>>(fs);
    }

    vector<string> myvector{"d", "e", "f"};
    writer->write_row(move(myvector));
    vector<string> myvector2{"a", "e", "f"};
    writer->write_row(move(myvector2));
    while (true) {}
}
```

Also is `ifstream` correct here?

`DelimWriter(const std::string& filename) : DelimWriter(std::ifstream(filename)) {};`

So what is the right way of construct a `DelimWriter` with a `string`?

**Comment by vincentlaucsb** [comment]
Why do you need to construct a `shared_ptr` over a CSVWriter? The reference exists because `std::ofstream` has no copy constructor. You don't need a smart pointer because `ofstream` automatically closes the file handle it owns when your code exits.

Stick to the example here: https://github.com/vincentlaucsb/csv-parser#writing-csv-files
```cpp
# include "csv.hpp"
# include ...

using namespace csv;
using namespace std;

...

stringstream ss; // Can also use ofstream, etc.
auto writer = make_csv_writer(ss);
writer << vector<string>({ "A", "B", "C" })
    << deque<string>({ "I'm", "too", "tired" })
    << list<string>({ "to", "write", "documentation." });

writer << array<string, 2>({ "The quick brown "fox", "jumps over the lazy dog" });
```

Here `auto writer` is really `CSVWriter<std::stringstream> writer`.

There is no way to construct a `DelimWriter` over an `std::ifstream` because that makes no sense. `DelimWriter` is used to write, and ifstream is used for reading files.

**Comment by tesla1060** [comment]
Hi, @vincentlaucsb 
my need is actually like below,

```
#include <iostream>
#include "csv.hpp"
#include <fstream>
#include <map>
#include <vector>
using namespace csv;
using namespace std;

class Recorder {
private:
    std::map<int, csv::CSVWriter<std::ofstream >> csv_writers;
    std::map<int, std::ofstream > ofstream_map;
public:
    Recorder();
};

Recorder::Recorder() {
    vector<int> keys = {1, 2, 3};
    for (auto key:keys) {
        stringstream s;
        s << "test" << key << ".csv";
        ofstream fs(s.str());
        ofstream_map[key] = move(fs);
        csv_writers[key] = csv::make_csv_writer(ofstream_map[key]);
    }
}

int main() {
    Recorder recorder;
    return 0;
}
```

This does compile, 

> error C2280: “csv::DelimWriter<std::ofstream,44,34> &csv::DelimWriter<std::ofstream,44,34>::operator =(const csv::DelimWriter<std::ofstream,44,34> &)”: 尝试引用已删除的函数

I am wondering what is wrong in my code?

Also this line was picking up from the orginal code of `csv.hpp`, which seems suppose to construct a `DelimWriter` out of a filename, but I wonder the same why `ifstream` is used here.

`        DelimWriter(const std::string& filename) : DelimWriter(std::ifstream(filename)) {};
`

**Comment by tesla1060** [comment]
> Hi, @vincentlaucsb
> my need is actually like below,
> 
> ```
> #include <iostream>
> #include "csv.hpp"
> #include <fstream>
> #include <map>
> #include <vector>
> using namespace csv;
> using namespace std;
> 
> class Recorder {
> private:
>     std::map<int, csv::CSVWriter<std::ofstream >> csv_writers;
>     std::map<int, std::ofstream > ofstream_map;
> public:
>     Recorder();
> };
> 
> Recorder::Recorder() {
>     vector<int> keys = {1, 2, 3};
>     for (auto key:keys) {
>         stringstream s;
>         s << "test" << key << ".csv";
>         ofstream fs(s.str());
>         ofstream_map[key] = move(fs);
>         csv_writers[key] = csv::make_csv_writer(ofstream_map[key]);
>     }
> }
> 
> int main() {
>     Recorder recorder;
>     return 0;
> }
> ```
> 
> This does compile,
> 
> > error C2280: “csv::DelimWriterstd::ofstream,44,34 &csv::DelimWriterstd::ofstream,44,34::operator =(const csv::DelimWriterstd::ofstream,44,34 &)”: 尝试引用已删除的函数
> 
> I am wondering what is wrong in my code?
> 
> Also this line was picking up from the orginal code of `csv.hpp`, which seems suppose to construct a `DelimWriter` out of a filename, but I wonder the same why `ifstream` is used here.
> 
> ` DelimWriter(const std::string& filename) : DelimWriter(std::ifstream(filename)) {};`

The reason I need to use `shared_ptr` in the `map` is because the assignment constructor is deleted.

```
    std::map<int, std::shared_ptr<csv::CSVWriter<std::ofstream >>> csv_writers;
    std::map<int, std::ofstream > ofstream_map;
```

**Comment by yuzu-ogura** [comment]
> > Hi, @vincentlaucsb
> > my need is actually like below,
> > ```
> > #include <iostream>
> > #include "csv.hpp"
> > #include <fstream>
> > #include <map>
> > #include <vector>
> > using namespace csv;
> > using namespace std;
> > 
> > class Recorder {
> > private:
> >     std::map<int, csv::CSVWriter<std::ofstream >> csv_writers;
> >     std::map<int, std::ofstream > ofstream_map;
> > public:
> >     Recorder();
> > };
> > 
> > Recorder::Recorder() {
> >     vector<int> keys = {1, 2, 3};
> >     for (auto key:keys) {
> >         stringstream s;
> >         s << "test" << key << ".csv";
> >         ofstream fs(s.str());
> >         ofstream_map[key] = move(fs);
> >         csv_writers[key] = csv::make_csv_writer(ofstream_map[key]);
> >     }
> > }
> > 
> > int main() {
> >     Recorder recorder;
> >     return 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This does compile,
> > > error C2280: “csv::DelimWriterstd::ofstream,44,34 &csv::DelimWriterstd::ofstream,44,34::operator =(const csv::DelimWriterstd::ofstream,44,34 &)”: 尝试引用已删除的函数
> > 
> > 
> > I am wondering what is wrong in my code?
> > Also this line was picking up from the orginal code of `csv.hpp`, which seems suppose to construct a `DelimWriter` out of a filename, but I wonder the same why `ifstream` is used here.
> > ` DelimWriter(const std::string& filename) : DelimWriter(std::ifstream(filename)) {};`
> 
> The reason I need to use `shared_ptr` in the `map` is because the assignment constructor is deleted.
> 
> ```
>     std::map<int, std::shared_ptr<csv::CSVWriter<std::ofstream >>> csv_writers;
>     std::map<int, std::ofstream > ofstream_map;
> ```

hi, how do you solve this problem?
