### ISSUE TITLE
Make dev settings an option

### ISSUE THREAD

**Issue by hsdk123** [vincentlaucsb/csv-parser#139]
Currently, the variable is automatically set based upon configuration, and hence this does not play well with cmake FetchContent. Would be great if this was made an option() instead. 

Reference: https://github.com/vincentlaucsb/csv-parser/blob/master/CMakeLists.txt#L42

**Comment by vincentlaucsb** [comment]
Just tested the latest version (with CMake updates). I didn't see any DEV specific options (like the unit test target or the target to generate a single header). Will close this.
