### ISSUE TITLE
will it support c++11 sometime later?

### ISSUE THREAD

**Issue by 7starsea** [vincentlaucsb/csv-parser#14]
I am wondering that will csv-parser support c++11 some time later?

Thanks.

**Comment by vincentlaucsb** [comment]
Maybe. The main C++17 feature this library uses is std::string_view to prevent copying a lot of strings around. If somebody could find a good C++11 string_view implementation then I could probably make this library C++11 compatible.

**Comment by 7starsea** [comment]
I know fmt (https://github.com/fmtlib/fmt) lib provide a string_view implementation called fmt::basic_string_view. 
see also http://fmtlib.net/latest/api.html#_CPPv2N3fmt11string_viewE.
I hope it helps.

**Comment by 7starsea** [comment]
here is another one:
https://github.com/bitwizeshift/string_view-standalone

**Comment by Kvaz1r** [comment]
There is also this one - [string-view-lite](https://github.com/martinmoene/string-view-lite)

**Comment by vincentlaucsb** [comment]
#19 should do the trick. Let me know if there's any issues.

**Comment by vincentlaucsb** [comment]
@Kvaz1r Thanks for the recommendation. It worked out perfectly!
