### ISSUE TITLE
Semicolon characters inside value fields fails the csv reading?

### ISSUE THREAD

**Issue by browser-bug** [vincentlaucsb/csv-parser#140]
I've noticed (and took me quite sometime to figure it out cause I wasn't expecting something like this) that the CSVReader fails in reading something like this:

```
name,type,values
algorithm,string,one/two/three
threads,int32_t,1;2:3;4
```

Using any other character makes it good:

```
name,type,values
algorithm,string,one/two/three
threads,int32_t,1/2/3/4
```

Can this be affected by the `;` traded for a csv separator in Windows format? Just guessing.
*Update*: specifying indeed the format brings correct results
```
CSVFormat format;
format.delimiter(',');
```

I don't know if this is expected but once the default delimiter is picked a semicolon should be harmless.

**Comment by vincentlaucsb** [comment]
This is probably caused by it confusing the guessing heuristic. When you have nested CSV columns like that, it's best to explicitly define the delimiter.
