### ISSUE TITLE
CSVWriter writes decimal part of floats incorrectly

### ISSUE THREAD

**Issue by oschonrock** [vincentlaucsb/csv-parser#142]
It's a simple typo I believe. This line:

https://github.com/vincentlaucsb/csv-parser/blob/621a9d94e4eab8acd31a8ac35577a68acdc1870f/include/internal/csv_writer.hpp#L64

should read:

```c++
        result += (decimal == 0) ? "0" : to_string(decimal);
```

great lib!

**Comment by vincentlaucsb** [comment]
Thanks for posting your bug report.

Yes, you're absolutely right.

**Comment by oschonrock** [comment]
thanks
