### ISSUE TITLE
Incorrect parsing of subunitary double values

### ISSUE THREAD

**Issue by foolnotion** [vincentlaucsb/csv-parser#15]
The following fails to parse correctly and causes the unit test to fail. 

```
std::string s("0.15");
long double out;    
REQUIRE(data_type(s, &out) == CSV_DOUBLE);
REQUIRE(is_equal(out, 0.15));
```

The parsed value is actually 1.5 instead of 0.15.

**Comment by vincentlaucsb** [comment]
Thanks for reporting this bug. I've fixed it in the latest release.
