### ISSUE TITLE
The last line is ignored

### ISSUE THREAD

**Issue by Starfa** [vincentlaucsb/csv-parser#151]
example.csv
id,name
1,hello
2,""
Three lines in total.
Last line without line break.

I try to get all rows of this csv file. And i found the last line is ignored.

**Comment by Starfa** [comment]
Can i fix it in this way?

CSV_INLINE void IBasicCSVParser::end_feed() {
        using internals::ParseFlags;
       
        bool empty_last_field = this->data_ptr
            && this->data_ptr->_data
            && !this->data_ptr->data.empty()
            && (parse_flag(this->data_ptr->data.back()) == ParseFlags::DELIMITER
                || compound_parse_flag(this->data_ptr->data.back()) == ParseFlags::QUOTE_ESCAPE_QUOTE);

        // Push field
        if (this->field_length > 0 || empty_last_field) {
            this->push_field();
        }

        // Push row
        if (this->current_row.size() > 0)
            this->push_row();
    }

**Comment by vincentlaucsb** [comment]
Thanks for your report. This was fixed in the latest commit.
