### ISSUE TITLE
Does not support Chinese  file path or Chinese characters in file?

### ISSUE THREAD

**Issue by Phymin** [vincentlaucsb/csv-parser#164]
Hi,

Thanks for providing such a great library, but when I test it with Chinese file path, the library will throw exception and says cannot open file, or I change the file path to English, but if the content in the file is Chinese, it cannot decode the characters correctly. So I was wondering if there is a way to fix this problem? Thank you.

**Comment by vincentlaucsb** [comment]
This is a CSV parsing library, not a Unicode decoding library. If you want to decode Chinese characters, you will need pair this library with a relevant library that can read Chinese characters. I wish you luck in your endeavor, but I do not have any experience in this area.
