### ISSUE TITLE
Hex string parsing supported?

### ISSUE THREAD

**Issue by ganler** [vincentlaucsb/csv-parser#169]
Hi thanks for the great work! I just want to quickly check if csv-parser is capable of parsing hex string to integers.

**Comment by vincentlaucsb** [comment]
Thank you for supportive comments. Currently, this feature does not exist. However, you could easily roll your own hex to int function and pass a parsed string_view or string through it.

But I will incorporate this in a future release.

**Comment by vincentlaucsb** [comment]
Implemented by #179
