### ISSUE TITLE
Floating point output completely broken?

### ISSUE THREAD

**Issue by Holt59** [vincentlaucsb/csv-parser#170]
The following:

```cpp
#include <iostream>
#include <csv.hpp>

int main(int argc, char* argv[]) {
    auto writer = csv::make_csv_writer(std::cout);
    writer << std::vector<std::string>{"a", "b", "c"};
    writer << std::make_tuple(1, 0.004654, 45);
}
```

Outputs:

```
a,b,c
1,0.465,45
```

Is there a way to fix this quickly? Otherwise, this makes this library completely unusable... 

Is there a reason not to use the standard `to_string` functions in the library?

**Comment by vincentlaucsb** [comment]
The standard to_string() functions are very slow. I also don't see how this "makes this library completely unusable". Yes this is a bug, but you can retrieve the parsed string and run any conversion function you want on it.

**Comment by Holt59** [comment]
> The standard to_string() functions are very slow. I also don't see how this "makes this library completely unusable". Yes this is a bug, but you can retrieve the parsed string and run any conversion function you want on it.

Are there any benchmarks? I'm working with kind of large CSV and I did not notice any performance difference when using the fix I provided that switch to `std::to_string`. 

Also, this is not related to parsing the string but writing it. I could do all the call to to_string manually but that's not very clean and I don't really see the benefits of using this if I have to do so.

**Comment by vincentlaucsb** [comment]
Bugs happen, even in "professionally developed" software. If I could only push code if I could guarantee it to be 100% bug free, I would never publish anything. You're asking a lot for software that is essentially provided for free.

My conversion functions also use long doubles to store integral components, so suggesting that the integral part of a large double won't fit in a long double is nonsense:

![image](https://user-images.githubusercontent.com/18455475/127076868-624c77cc-1654-4ba9-9805-95ff6630b13e.png)

**Comment by vincentlaucsb** [comment]
You do have a point about large doubles--that will be fixed.

**Comment by vincentlaucsb** [comment]
Should be fixed by #177. Arbitrarily large ints stored in doubles should be outputted correctly as well.

**Comment by Holt59** [comment]
I did not mean to be harsh, it's just that this is a hard-to-detect bug that's very impacting - it took me hours to notice that the issue was not in my computation code but in the writer part.

Just to point-out, none of the tests you wrote here https://github.com/vincentlaucsb/csv-parser/blob/master/tests/test_write_csv.cpp#L13-L26 are actually checking the bug above (leading zeros in the decimal part), so maybe it'd be worth adding some (although I think the new code is correct, but better safe than sorry).

**Comment by vincentlaucsb** [comment]
You're right. I will reopen this so I can add the appropriate unit tests.
