### ISSUE TITLE
I try to use  foreach to get data twice， but I  only got one valid data.why?

### ISSUE THREAD

**Issue by BisonReto** [vincentlaucsb/csv-parser#174]
the  code is：
        CSVReader reader("persons.csv");

	long long int sum = 0;
	std::stringstream my_json;
	vector<int> age_list;
	for (CSVRow& row:reader)
	{
		age_list.push_back(row["Age"].get<int>());
	}
	cout << "age size is " << age_list.size() << endl;

        cout << "row is " << reader.n_rows() << endl;
	vector<int> it_list;
	for (CSVRow& row:reader)
	{
		it_list.push_back(row["Age"].get<int>());
	}
	cout << "it size is " << it_list.size() << endl;
but the output is：
age size is 50000
row is 49999
it size is 0

**Comment by vincentlaucsb** [comment]
CSVReader iterators over a file are only meant to iterate over a file once. They are input iterators--one you process the entire input, you are done.

**Comment by BisonReto** [comment]
Thanks!
