### ISSUE TITLE
csv::set_decimal_places does not round decimals to width

### ISSUE THREAD

**Issue by telmo-carmo** [vincentlaucsb/csv-parser#182]
csv::set_decimal_places(2);
writer << std::make_tuple(-1.043, 2.126, "Three");  // out =>  -1.04;2.12;Three

**Comment by vincentlaucsb** [comment]
Closing as this is the intended behavior. It is the user's responsibility to call `std::round()` on CSV writer inputs. I do not believe all users should be saddled with the cost of calling `std::round` on all floating point inputs.
