### ISSUE TITLE
Conversion of float/double in CSVWriter is broken

### ISSUE THREAD

**Issue by jleugeri** [vincentlaucsb/csv-parser#188]
Hi, I noticed a critical bug:
when trying to save values close to 10^n for some n (e.g. 1000.0, 1000000.0), the leading decimal is **missing** in the exported .csv file (e.g. the string is saved as "000.0" or "000000.0", respectively).
I traced this behaviour back to the way the digits are serialized in [csv_writer.hpp](https://github.com/vincentlaucsb/csv-parser/blob/master/include/internal/csv_writer.hpp#L57).

The problem comes from the fact that the log(x)/log(10) is an imprecise method to estimate the number of digits of x, as speculated e.g. in this [question on stackoverflow](https://stackoverflow.com/questions/1489830/efficient-way-to-determine-number-of-digits-in-an-integer). 

To verify that this is indeed the problem, I tested the following minimal (non-)working example (I'm compiling with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on WSL, but the behaviour should be the same regardless of compiler):

```C++
#include <iostream>
#include <math.h>

int main() {
    double d = 1000.0;
    double integral_part;
    double fractional_part = std::abs(std::modf(d, &integral_part));
    integral_part = std::abs(integral_part);

    int n_digits = (int)(std::log(integral_part) / std::log(10));
    std::cout << "d: " << d << ", integral_part: " << integral_part << ", fractional_part: " << fractional_part << ", log(integral_part): " << std::log(integral_part) << ", log(10): " << std::log(10) << ", n_digits: "<< n_digits << std::endl;
    
    // Produces:
    // d: 1000, integral_part: 1000, fractional_part: 0, log(integral_part): 6.90776, log(10): 2.30259, n_digits: 2

    // Should produce:  ------------------------------------------------------------------------------------------------------v
    // d: 1000, integral_part: 1000, fractional_part: 0, log(integral_part): 6.90775527898, log(10): 2.30258509299, n_digits: 3
    
    return 0;
}
```

I believe this is a breaking error, because right now it may invalidate data in a way that is very hard to spot (at least it took me a long time to find). If the fix means taking a slower algorithm for serialization, I'd be fine with that, because correctness > speed (for me at least).
Best regards and thanks for your work on this library!

**Comment by vincentlaucsb** [comment]
Should be fixed in the latest release
