### ISSUE TITLE
How do you use this with a MFC based application?

### ISSUE THREAD

**Issue by ajtruckle** [vincentlaucsb/csv-parser#189]
I am building with the newer C++17 etc but I want to read in cells as either:

CString

or

COleDateTime

I can't work it out.

Thanks.

**Comment by vincentlaucsb** [comment]
I'm sorry but I wouldn't have a clue as MFC is older than I am

**Comment by ajtruckle** [comment]
ROTFL - a reply 5 months later ... :)

Thanks all the same! 

I used an alternative CSV library.

**Comment by bangusi** [comment]
You can construct CString from std::string.
I am curious which CSV library you used that went out of its way to accommodate CString.

**Comment by ajtruckle** [comment]
I should of clarified. I ended up adding my CSV requirements into my C# COM DLL support library. So used CsvHelper. Then I called my interface DLL functions from MFC.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
