### ISSUE TITLE
Pre Decrement not defined

### ISSUE THREAD

**Issue by rtolsma** [vincentlaucsb/csv-parser#192]
https://github.com/vincentlaucsb/csv-parser/blob/f65b6a72ece010f0bee7cfb3ef91b0e07f14eabc/single_include/csv.hpp#L6286

Method for decrement is declared here, but the implementation does not seem to actually be defined anywhere, which results in a link error.

**Comment by vincentlaucsb** [comment]
Thanks for your report. This was removed in the latest version.
