### ISSUE TITLE
The empty function is totally wrong in the csv-parser

### ISSUE THREAD

**Issue by freshduer** [vincentlaucsb/csv-parser#197]
![image](https://user-images.githubusercontent.com/72605280/167976989-543e816a-0db3-4e22-bf1c-3b74f4776149.png)
the empty() uses the n_rows() ,but n_rows() returns the number of rows that have been read so far,which is totally not right for the empty func.
i suppose this should be modified , turn the n_rows() into some else

**Comment by vincentlaucsb** [comment]
empty() = "Whether or not the file or stream contains valid CSV rows".

If there is a valid CSV row, n_rows => 1. Because empty() returns n_rows, empty() >= 1 if there is a valid CSV row.

Therefore empty() does what it's supposed to. QED.

**Comment by freshduer** [comment]
> 
maybe u can try to use csv reader to load a csvfile and then use empty() function to see whether the return value is 0 or not
it appears to me that the result is always 0
----n_rows() returns the number of rows that have been read so far,but if you do not use the read_row() function,the _n_rows is always 0

**Comment by freshduer** [comment]
> empty() = "Whether or not the file or stream contains valid CSV rows".
> 
> If there is a valid CSV row, n_rows => 1 (see pic). Because empty() returns n_rows, empty() >= 1 if there is a valid CSV row.
> 
> Therefore empty() does what it's supposed to. QED.
> 
> ![image](https://user-images.githubusercontent.com/18455475/168740863-c491b505-0fd3-4f2b-87a9-4bf3807ef505.png)

maybe u can try to use csv reader to load a csvfile and then use empty() function to see whether the return value is 0 or not
it appears to me that the result is always 0
----n_rows() returns the number of rows that have been read so far,but if you do not use the read_row() function,the _n_rows is always 0

**Comment by freshduer** [comment]
@vincentlaucsb 
maybe u can try to use csv reader to load a csvfile and then use empty() function to see whether the return value is 0 or not
it appears to me that the result is always 0
----n_rows() returns the number of rows that have been read so far,but if you do not use the read_row() function,the _n_rows is always 0
