### ISSUE TITLE
Quote character not removed properly

### ISSUE THREAD

**Issue by zazolabs** [vincentlaucsb/csv-parser#201]
If there is a space after the comma, i.e.

val1, val2, <space here>  "val3", val4

the col[2] is "val3 - it is trimmed but the first quote is not removed.

val1, val2,"val3", val4

without space it gives the correct result.

**Comment by vincentlaucsb** [comment]
This CSV parser was intended to parse fields delimited by a single delimiter whether it be comma, tab, pipe, etc.

By having a space after the comma, you essentially have fields delimited by two characters (comma + space) `, `.

That's beyond the scope of this library and I don't see an easy way to accommodate it.
