### ISSUE TITLE
The documentation site is not working

### ISSUE THREAD

**Issue by aayush749** [vincentlaucsb/csv-parser#210]
I tried opening the parser's documentation at https://vincentlaucsb.github.io/csv-parser/. But there seems to be some problems as it isn't working.

**Comment by agribov** [comment]
Still the same issue, but with a different broken URL - The Readme.md points to https://vincentlaucsb.github.io/csv-parser/html/ which is also a broken link. @vincentlaucsb

**Comment by vincentlaucsb** [comment]
Should be fixed in the latest README
