### ISSUE TITLE
float values with leading '+' are not recognized

### ISSUE THREAD

**Issue by goranobradovic1** [vincentlaucsb/csv-parser#213]
Leading plus signs ('+') seems to be unsupported in the `data_type(...)` function in the csv.hpp, so in this example all numbers are classified as `DataType::CSV_STRING`.

 +60.00000,  +1.24889,  +0.00000
 +60.01000,  +0.24978,  +0.00000
.....

Best regards
Goran

**Comment by vincentlaucsb** [comment]
Thanks for your report. This has been fixed in the latest version.
