### ISSUE TITLE
csv single_header slow to read data..

### ISSUE THREAD

**Issue by dangdkhanh** [vincentlaucsb/csv-parser#219]
CSVReader reader("100k rows.csv");

```
for (CSVRow& row: reader) { // Input iterator
    for (CSVField& field: row) {
        auto k= field.get<std::string>();
      ...
    }
}
```

I tested with this file.
However it takes 10s to read entire rows.
Please check? [Link](https://drive.google.com/file/d/1QcSwkeopH1YGHf4vvi11t57sef33CE-Z/view?usp=sharing)

**Comment by DylanBT928** [comment]
The link you provided requires access. Could you change the sharing permissions to anyone with link?

**Comment by dangdkhanh** [comment]
Hi @DylanBT928 ,
Sorry. After further investigation, my internal calls were the cause.
Now the code is working fine.

**Comment by dangdkhanh** [comment]
Hi @DylanBT928 ,
I tried another csv sample and it seems to have the problem.
I have updated csv link.
Thanks you!
