### ISSUE TITLE
Fields with embedded newlines

### ISSUE THREAD

**Issue by melton1968** [vincentlaucsb/csv-parser#221]
I am loading a csv file produced by PostgreSQL. Some of the fields have embedded newlines:

    abc,"def\nghi",123,
    xyz,"rst\nuvw",456,

Should the parser handle this case? 

It complains that the row has to few columns.

**Comment by vincentlaucsb** [comment]
![image](https://github.com/vincentlaucsb/csv-parser/assets/18455475/145e251d-3769-49a7-8c61-41a302f27a70)

Yes it should. The warning is probably because of the trailing comma after every row.

**Comment by vincentlaucsb** [comment]
Added some unit tests and verified that embedded newline handling works, even when the last row is empty.

With that being said, my experience with PostgreSQL and it's COPY TO CSV function is that it works very well and does not produce empty columns at the end.

Closing as I'm not sure what there is to fix.
