### ISSUE TITLE
Parsing broken on cursed newlines

### ISSUE THREAD

**Issue by msrd0** [vincentlaucsb/csv-parser#223]
I have a cursed input file (that I do not control, obviously) that uses `\r\r\n` (hex `0D 0D 0A`) as newlines. This makes the parser produce rows that are (a) not considered empty, so I can't easily skip them, but (b) contain only the first column. It would be nice if this library either accepted any cursed combination of newline'ish characters as a single newline, or allows for the user to specify which combination of characters to treat as a newline.

**Comment by vincentlaucsb** [comment]
Thanks for your report. The latest version should be able to gracefully handle `\r\r\n` (or any other combination of `\r` and `\n`.
