### ISSUE TITLE
csv-writer problem?

### ISSUE THREAD

**Issue by dangdkhanh** [vincentlaucsb/csv-parser#224]
Hi,
```
std::ofstream infile;
infile.open(f, std::ios::out | std::ios::trunc);
auto writer = make_tsv_writer(infile);
```
I used to csvwriter to write the following lines
`writer << vec;`

```
A.	887CE64AE586C40550C65DEE765EE3A6
B.	C9CD937BF0318C2309DF1CE6AA93142D
C.	2BAEB38E26F2AFB093F0D5AC6CF224AD
D.	470A32CCE2760A42F4C5ECB3D57186E5
E.	6E2E630653E45422A3C9809994EB313E
```

then I get this output
![image](https://github.com/vincentlaucsb/csv-parser/assets/99936463/b0bbae28-6001-4203-a64f-4efb35b6e486)

but if I remove a dot behind A, the result is returned as expected:
```
A	887CE64AE586C40550C65DEE765EE3A6
B.	C9CD937BF0318C2309DF1CE6AA93142D
C.	2BAEB38E26F2AFB093F0D5AC6CF224AD
D.	470A32CCE2760A42F4C5ECB3D57186E5
E.	6E2E630653E45422A3C9809994EB313E
```

![image](https://github.com/vincentlaucsb/csv-parser/assets/99936463/8fbda488-99a4-4b7a-874d-8ca7b56a3677)

Is there any problem?

**Comment by vincentlaucsb** [comment]
Looks like a problem with whatever you are using to read the file (Notepad?) and not the library. The CSV writing code is very simple (joining items with the delimiter) and it's hard to see how random Chinese characters could result from just ASCII input.

![image](https://github.com/vincentlaucsb/csv-parser/assets/18455475/b1bc06f5-ccd3-4165-9ee4-3aab26577a72)
