### ISSUE TITLE
Very minor readme issue

### ISSUE THREAD

**Issue by ClancyWalters** [vincentlaucsb/csv-parser#225]
The example at [README.md](https://github.com/vincentlaucsb/csv-parser?tab=readme-ov-file#handling-variable-numbers-of-columns) should be updated from `VariableColumnPolicy::IGNORE` to `VariableColumnPolicy::IGNORE_ROW`

**Comment by vincentlaucsb** [comment]
You're right. Thank you for pointing this out.
