### ISSUE TITLE
Values between 0 and -1 are exported positive

### ISSUE THREAD

**Issue by PabloElSegundo** [vincentlaucsb/csv-parser#230]
All exported double values between 0 and  -1 are positive. Your test cases do not test this. 
This issue ist due to an error in the csv.hpp file in line 6641. 
There you need to change result = "0"; to result += "0";". Otherwise you overwrite the sign. 

I can currently not open a PR. I try to make the fix on the weekend.

**Comment by vincentlaucsb** [comment]
Thank you for your report. This has been fixed.
