### ISSUE TITLE
which branch should I use?

### ISSUE THREAD

**Issue by huyuguang** [vincentlaucsb/csv-parser#24]
Master branch or single-header branch?
I prefer the single-header branch, but is the branch stable, and what's the difference between master with single-header?

**Comment by huyuguang** [comment]
It seems that you rewrote everything recently, I just tried single-header, it works, but the compiler report some warnings:
 ```
csv.hpp line 1035: variable row not used
 csv.hpp line 1109 variable col_names hide membership col_names
 csv.hpp line 1280 parameter close never used
```

**Comment by vincentlaucsb** [comment]
The single header is experimental and a few versions behind. Master has the latest updates. Once I have time I'll update the single header branch and merge it in.
