### ISSUE TITLE
Why is the first column ignored?

### ISSUE THREAD

**Issue by bangusi** [vincentlaucsb/csv-parser#36]
Windows 10, Visual Studio 2017
**My data**
```
EMPLOYEEKEY	FIRSTNAME	HIREDATE	LASTNAME	TITLE	
2	Kevin	2006-08-26	Brown	Marketing Assistant	
3	Roberto	2007-06-11	Tamburello	Engineering Manager	
4	Rob	2007-07-05	Walters	Senior Tool Designer	
5	Rob	2007-07-05	Walters	Senior Tool Designer	
6	Thierry	2007-07-11	D'Hers	Tool Designer	
7	David	2007-07-20	Bradley	Marketing Manager	
8	David	2007-07-20	Bradley	Marketing Manager	
9	JoLynn	2007-07-26	Dobney	Production Supervisor - WC60	
10	Ruth	2007-08-06	Ellerbrock	Production Technician - WC10
```
**My Code**
```
void f0()
{
	csv::Reader foo;

	foo.configure_dialect("my_dialect")
		.delimiter("\t")
		.quote_character('"')
		.double_quote(true)
		.skip_initial_space(false)
		.trim_characters(' ', '\t')
		//	.ignore_columns("foo", "bar")
		.header(true)
		.skip_empty_rows(true);

	foo.read("sample.csv");
	auto rows = foo.rows();
	for (auto& row : rows)
	{
		auto key = row["EMPLOYEEKEY"];
		auto fname = row["FIRSTNAME"];
		auto hdate = row["HIREDATE"];
		auto lname = row["LASTNAME"];
		auto title = row["TITLE"];
		std::cout << key << " " << fname << " " << hdate << " " << lname << " " << title << "\n";
	}

```}

**Outpu**t
```
 Kevin 2006-08-26 Brown Marketing Assistant
 Roberto 2007-06-11 Tamburello Engineering Manager
 Rob 2007-07-05 Walters Senior Tool Designer
 Rob 2007-07-05 Walters Senior Tool Designer
 Thierry 2007-07-11 D'Hers Tool Designer
 David 2007-07-20 Bradley Marketing Manager
 David 2007-07-20 Bradley Marketing Manager
 JoLynn 2007-07-26 Dobney Production Supervisor - WC60
 Ruth 2007-08-06 Ellerbrock Production Technician - WC10
```

**Comment by bangusi** [comment]
My apologies. Wrong library

**Comment by vincentlaucsb** [comment]
If you use my library you won't run into these problems ;)

**Comment by bangusi** [comment]
I am using your library now. Since your are here. I have a couple of questions:
1) Why does specifying the delimiter e.g.
`csv::CSVFormat format = { '~','"','1',{},true,true };`
slow it down considerably
2) My data is delimited by a tilde '~' . Is it possible to add this in the default list of guesses.
Asking because so far I am not able to get the library to parse my file which is tilde delimited even when I pass the format argument to the constructor.

**Comment by vincentlaucsb** [comment]
It would be really helpful if you could provide your raw data file or a small portion of it as well as the code you are using.

**Comment by bangusi** [comment]
**My data: sample.csv**
```
EMPLOYEEKEY~FIRSTNAME~HIREDATE~LASTNAME~TITLE~
2~Kevin~2006-08-26~Brown~Marketing Assistant~
3~Roberto~2007-06-11~Tamburello~Engineering Manager~
4~Rob~2007-07-05~Walters~Senior Tool Designer~
5~Rob~2007-07-05~Walters~Senior Tool Designer~
6~Thierry~2007-07-11~D'Hers~Tool Designer~
7~David~2007-07-20~Bradley~Marketing Manager~
8~David~2007-07-20~Bradley~Marketing Manager~
9~JoLynn~2007-07-26~Dobney~Production Supervisor - WC60~
10~Ruth~2007-08-06~Ellerbrock~Production Technician - WC10~
```
`My code:`
```
//	csv::CSVFormat format = { '~','"','1',{},true,true }; // this makes it very slow and does not produce expected result
//	csv::CSVReader reader("sample.csv", format);
	csv::CSVReader reader("sample.csv");
	for (csv::CSVRow& row : reader)
	{ 
		for (csv::CSVField& field : row) 
		{
			std::cout << field.get<>() << "\t";
		}
		std::cout << "\n";
	}
```
**Output:**
```
2~Kevin~2006-08-26~Brown~Marketing Assistant~
3~Roberto~2007-06-11~Tamburello~Engineering Manager~
4~Rob~2007-07-05~Walters~Senior Tool Designer~
5~Rob~2007-07-05~Walters~Senior Tool Designer~
6~Thierry~2007-07-11~D'Hers~Tool Designer~
7~David~2007-07-20~Bradley~Marketing Manager~
8~David~2007-07-20~Bradley~Marketing Manager~
9~JoLynn~2007-07-26~Dobney~Production Supervisor - WC60~
10~Ruth~2007-08-06~Ellerbrock~Production Technician - WC10~

```

**Comment by bangusi** [comment]
@vincentlaucsb
Did you have a chance to take another look at this issue? If you need more info regarding my environment let me know.

**Comment by vincentlaucsb** [comment]
You need to use

```csv::CSVFormat format = { '~','"',0,{},true,true };```

assuming your header is on the first row. The reason why it slows it down is because since it accurately parses the data, it has to save the index of where each column starts. I'm currently working on an improvement to reduce the cost of creating these indices. It has a huge impact and I'll merge it in once I resolve compiler compatibility issues.

**Comment by bangusi** [comment]
Thank you.
