### ISSUE TITLE
Bug: Delimiter guessing overwrites column names.

### ISSUE THREAD

**Issue by amlatyrngom** [vincentlaucsb/csv-parser#44]
I observed that the col_names vector is overwritten when I pass in multiple delimiters.
This is because the `CSVReader::CSVReader(csv::string_view filename, CSVFormat format)` constructor overrides the format object that's passed in.

**Comment by vincentlaucsb** [comment]
I think I see the bug you're talking about it. Thanks for reporting it.

**Comment by vincentlaucsb** [comment]
Fixed by #46
