### ISSUE TITLE
Remove separate Makefile. Use CMakeLists for all building/testing tasks.

### ISSUE THREAD

**Issue by vincentlaucsb** [vincentlaucsb/csv-parser#51]

**Comment by LinuxDevon** [comment]
I was taking a look into this and is the makefile even still used? I try it and it is missing `csv_parser` target. 

I was working with the cmake file and it looks like you don't have a check for update gcc to version 8 like you do in the makefile. On Ubuntu the default is 7 on Ubuntu and when i try to use c++17 this doesn't have the header file `<charconv>` which doesn't appear till version 8. 

What is the status of this issue?

**Comment by vincentlaucsb** [comment]
The Makefile is really only used for code coverage purposes. I've tried using a popular CMake code coverage configuration but had some difficulty.

**Comment by peza8** [comment]
Just FYI @vincentlaucsb - I'm using csv-parser in a large project where all the build is managed by CMake, and I like to compile and link external libs (to improve build time for modified proprietary project files). 

I had an issue linking the csv-parser on MacOS. It was having issues linking the code coverage tests. 

I fixed it by removing this section from the CMakeLists.txt: 
```
if(MSVC)
	# Make Visual Studio report accurate C++ version
	# See: https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
  # /Wall emits warnings about the C++ standard library
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc /Zc:__cplusplus /W4")
else()
	# Ignore Visual Studio pragma regions
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unknown-pragmas")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} --coverage -Og")
endif(MSVC)
```

It would be great if there was a way to build the library for end users without running any code coverage tests (obviously a development process).

**Comment by vincentlaucsb** [comment]
Closing this as CMake has been used as the main build system for a while now.
