### ISSUE TITLE
Cannot build master

### ISSUE THREAD

**Issue by jgbradley1** [vincentlaucsb/csv-parser#58]
Something is wrong with the master branch. I am unable to build (using cmake) in a clean environment.

```
docker run -it ubuntu bash
> apt-get update -y && apt-get upgrade -y
> apt-get install -y build-essential doxygen git cmake make python3-dev python3
> git clone https://github.com/vincentlaucsb/csv-parser.git
> cd cdv-parser
> mkdir build
> cd build
> cmake -DCSV_CXX_STANDARD=11 ../
> make
```

This is the initial error message that appears:
```
/csv-parser/programs/data_type_bench.cpp:1:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
programs/CMakeFiles/data_type_bench.dir/build.make:62: recipe for target 'programs/CMakeFiles/data_type_bench.dir/data_type_bench.cpp.o' failed
make[2]: *** [programs/CMakeFiles/data_type_bench.dir/data_type_bench.cpp.o] Error 1
CMakeFiles/Makefile2:184: recipe for target 'programs/CMakeFiles/data_type_bench.dir/all' failed
make[1]: *** [programs/CMakeFiles/data_type_bench.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```
I see the same error when trying to build for C++17.

**Comment by vincentlaucsb** [comment]
It seems like your C++ compiler is missing some of the later C++17 libraries. But with that being said, the program that can't compile simply benchmarks this parser's number parsing against the standard library's. Since it's not that important I'll just comment out the building instructions for that program.

**Comment by madGambol** [comment]
I went back to gcc-5/g++-5 through gcc-8/g++-8 ... no joy. Where did that header drop out?

**Comment by madGambol** [comment]
Under Pop-Os 19.10, "make" quits building at:
> [ 58%] Linking CXX executable single_include_test
> /usr/bin/ld: CMakeFiles/single_include_test.dir/file1.cpp.o: in function pthread_create'
> /usr/bin/ld: CMakeFiles/single_include_test.dir/file2.cpp.o: in function pthread_create'
> collect2: error: ld returned 1 exit status

 ??? libpthread is present on the system. 

The following complete normally:
*  depend
* rebuild_cache
* generate_single_header
* edit_cache
* doxygen
* csv
* csv_info
* csv_stats
* csv_guess_bench
* csv_bench
* csv_test

The ones left not working are:
* all
* csv_generate_bench (missing data?)
* single_include_test (thread complaint)

 Are they in the proper order in that list? Is there a "git pull --recurse-submodule" type command needed to fill in the modules?
So it's in usable shape.
