### ISSUE TITLE
API can not handle files with thousands of columns

### ISSUE THREAD

**Issue by leoxtc** [vincentlaucsb/csv-parser#61]
I have a file with 16k columns and the API can not parse it. 

Column names are nor parsed correctly neither the lines

Can I send a example file?

**Comment by leoxtc** [comment]
Here is a sample file. 

It apparently load the headers fine, but try to print the last column name and you will see the error.
It somehow concatenate previous column names.

[sample.csv.gz](https://github.com/vincentlaucsb/csv-parser/files/3847549/sample.csv.gz)

**Comment by vincentlaucsb** [comment]
The header row doesn't end with a `;`, but all the other rows do. As a result, the CSV reader interprets all of the data as being oversized (one column too big) so it discards them. You can deal with this by adding a semi-colon to the end of the header row (easiest) or by [overriding CSVReader's behavior](http://vincela.com/csv/md_docs_source_variable_row_lengths.html).
