### ISSUE TITLE
try catch not working in CSVReader object if strict parsing is there

### ISSUE THREAD

**Issue by self-tuts** [vincentlaucsb/csv-parser#62]
The CSVFormat object is below
```
 CSVFormat csvFileFormat;
 csvFileFormat.column_names("name,age");
 csvFileFormat.strict_parsing();
```

The data in csv file is like 

A,10
B,5000
C,30
D,100
E,100,5000

Note that the fifth row has three columns.

I am creating a csv reader object but it is not catching the std::runtime_error during the csv reader object creation

```
try {
        CSVReader reader(filePath,csvFileFormat);
}catch(std::runtime_error& e){
   std::cout << "Error" << std::endl;
}
```

**My main motive is to get all the malformed records present inside the csv file so that I can write those malformed records in a separate file.**

**Comment by vincentlaucsb** [comment]
Errors with data will be thrown while reading the data. but currently errors are only thrown for missing quotes (maybe I should document that better).

You can read [http://vincela.com/csv/md_docs_source_variable_row_lengths.html](this) to see how to get malformed records. I'm not sure if I like the current API for doing so, so let me know how you feel.

**Comment by vincentlaucsb** [comment]
Malformed row handling will be made easier by #66
