### ISSUE TITLE
How can I get the list of records that don't contain the exact number of columns as provided in the header

### ISSUE THREAD

**Issue by self-tuts** [vincentlaucsb/csv-parser#63]
This means that let's say that total number of header columns are 5

- First record has 5 comma separated values
- Second record has 8 comma separated values
- Third record has 2 comma separated values

From the above scenario we can say that the record second and third are invalid as the number of column is more than the number of header column in second record
and the number of column in third record is less than the number of header column

**### I want to get these error records so that I can dump then in some new file.**

Please Help

**Comment by vincentlaucsb** [comment]
Hi there, please refer to my response to #62
