### ISSUE TITLE
More elegant way to handle error?

### ISSUE THREAD

**Issue by zingdle** [vincentlaucsb/csv-parser#68]
```
#include "csv.hpp"

int main() {
  csv::CSVFormat format;
  format.delimiter('|').column_names({"A", "B", "C"});

  csv::CSVReader csv("foo.dat", format);

  for (auto& row : csv) {
    std::cout << row.to_json() << std::endl;
  }

  return 0;
}
```
with `foo.dat`:

```
1|2|3|
2|3|4|
```

causes `segmentation fault`.

Changing to `column_names({"A", "B", "C", "dummy"});` will do the job.

Is there any elegant way to catch such error than a segment fault? Also, Is there any option to handle such "dummy" column?

**Comment by vincentlaucsb** [comment]
The CSV parser rejects any rows that aren't the same length of the column name, so the best solution is to use an empty string ("") for the column name. The segfault happens because you're attempting to convert an empty row, but I've fixed it in #70 so it just returns an empty object instead.
