### ISSUE TITLE
Remove a misplaced delete statement

### ISSUE THREAD

**Issue by elfring** [vincentlaucsb/csv-parser#7]
Would you like to [remove a statement](https://github.com/vincentlaucsb/csv-parser/blob/00f2d2bcddec438b482d94d96bac31e1ca421969/src/csv_reader.cpp#L567 "Update candidate: CSVReader::read_csv_worker()") like the following because a null pointer should not be used for deletion?

```diff
             if (!in) { // Nullptr --> Die
-                delete in;
                 break;    
             }
```

**Comment by vincentlaucsb** [comment]
Fixed in 8d4a98e1910b0f7eadaec519959c21bc5bc5766e
