### ISSUE TITLE
This csv file crashes the parser

### ISSUE THREAD

**Issue by bangusi** [vincentlaucsb/csv-parser#71]
This file crashes the parser. The file is parsed correctly in Excel and OpenOffice/LibreOffice
My code:
```
void f0()
{
	csv::CSVFormat format;
	format.delimiter(',').quote('"').header_row(0);
	csv::CSVReader reader("problem.txt",format);
	auto column_names = reader.get_col_names();
	std::cout << column_names.size() << std::endl;
	for (auto& cv : column_names)
	{
		std::cout << cv << "\t";
	}
	std::cout << "\n";

	for (csv::CSVRow& row : reader)
	{
		std::cout << row.size() << std::endl;
		for (auto& rv : row)
		{
			std::cout << rv << "\t";
		}
		std::cout << "\n";
	}
}
The data:
```
ACCOUNT_TYPE,ACCOUNT_NUMBER,TRANSACTION_DATE,CHEQUE_NUMBER,DESCRIPTION1,DESCRIPTION2,CAD,USD
Chequing,07451-1007186,1/2/1987,,"Bill Payment","Purchase Order",-4.00,,
Saving,07451-1007186,1/29/1987,,"Account Payable Pmt","Mac 6000 INCO",210424.25,,
Chequing,07451-1007186,2/1/1987,,"Misc Payment","Purchase Order",-200.00,,
Chequing,07451-1007186,2/5/1987,,"Membership fees","VAT-Y 4007633",-917.33,,
Chequing,07451-1007186,2/5/1987,,"Membership fees","TXINS 4007659",-950.69,,
Saving,07451-1007186,2/26/1987,,"Account Payable Pmt","Mac 6000 INCO",79034.35,,
Chequing,07451-1007186,2/28/1987,,"Membership fees","VAT-Y 7453902",-7905.02,,
Chequing,07451-1007186,2/28/1987,,"Membership fees","TXINS 7454013",-823.93,,
Chequing,07451-1007186,3/1/1987,,"Bill Payment","Purchase Order",-8.00,,
Saving,07451-1007186,3/4/1987,,"Online transfer sent - 1872","Great Outdoors",-17000.00,,
```

**Comment by vincentlaucsb** [comment]
Your header row has 7 commas (8 columns) while your data rows have 8 commas (9 columns). 

You'll either want to strip out the extra commas before sending it through the CSVReader or creating your own subclass of CSVReader which overrides `bad_row_handler` such as here: https://github.com/vincentlaucsb/csv-parser/blob/master/include/internal/csv_reader.cpp#L34

**Comment by bangusi** [comment]
OK. But I would have though the library should not silently fail when encountering such files.
BTW I did not create this file, it was generated by some bank so it is a legitimate case of csv files one may encounter in real life. As mentioned above office applications such as LibreOffice are able to handle it.

**Comment by vincentlaucsb** [comment]
I agree there should probably be a warning when the majority of rows are rejected.

However, I don't think it's a reasonably formatted CSV file. I don't know why you'd add an extra comma to your data rows when there's not one in your header row. I've heard of it before, but it's not present in the majority of CSV files.

This CSV parser is also capable of handling it, you just need to tell it that it's a weird file. I think the easiest way to do it is to just turn the header row off, use auto-detection, and use `bad_row_handler` to capture the header row. I built this parser mainly to load CSV files into databases or run data analysis on them, which is why it's a bit anal about the column count.

**Comment by bangusi** [comment]
Another suggestion would be to provide a configuration option that allows the user to ignore extra rows. I have seen this feature in other file import (into database ) utilities.

**Comment by bangusi** [comment]
I just noticed that this issue #66  is supposed to address the same problem that I reported in #77.
Looking forward to the enhancement.
o called "Malformed rows" are actually not rare in csv files.

**Comment by vincentlaucsb** [comment]
The new version should handle variable length-rows in a first-class manner

**Comment by bangusi** [comment]
Wondering what the expected behaviour should be after the fix.
Now the library instead of crashing is simply silently fails ( stops processing the file ).
Is there a configuration change I need to make? 
All I did was download `version 1.3.0`  the run against the same input file that was crashing it.

**Comment by vincentlaucsb** [comment]
Try passing in a CSVFormat where you set `variable_columns(true)`

Example: https://github.com/vincentlaucsb/csv-parser#handling-variable-numbers-of-columns

**Comment by bangusi** [comment]
Yes, now works.

**Comment by vincentlaucsb** [comment]
Good to hear.
