### ISSUE TITLE
full range of uint16_t not handled by get()

### ISSUE THREAD

**Issue by edgimar** [vincentlaucsb/csv-parser#73]
A uint16_t should handle values from 0 to 65535, however when a string containing the value 65535 is parsed using CSVRow.get<uint16_t>(), it reports a C++ overflow error exception.

**Comment by vincentlaucsb** [comment]
Unfortunately, I never got around to setting unsigned integer limits, so right now CSVRow.get<uint_16t> is basically the same as CSVRow.get<int_16t> limits-wise.

Thanks for reminding me.

**Comment by vincentlaucsb** [comment]
Fixed in the latest release. Thanks again for reporting.
