### ISSUE TITLE
charconv isn't checked by cmake step

### ISSUE THREAD

**Issue by madGambol** [vincentlaucsb/csv-parser#74]
cmake complains about Doxygen being missing but goes on without it OK. During the make, I get this:
>[ 45%] Building CXX object programs/CMakeFiles/csv_generator.dir/csv_generator.cpp.o
/home/chris/Apps/CsvParser/programs/csv_generator.cpp:2:10: fatal error: charconv: No such file or directory
>#include \<charconv\>
>                ^~~~~~~~~~
>compilation terminated.
>programs/CMakeFiles/csv_generator.dir/build.make:62: recipe for target 'programs/CMakeFiles/csv_generator.dir/csv_generator.cpp.o' failed

This is with clang++ 6.0.0-1ubuntu2 . That little ^ pointer is actually under "<" in the header reference.

BTW, what package includes that header?

Thanks
madGambol

**Comment by LinuxDevon** [comment]
I got this same error too. I was using Ubuntu 18.04 which comes with gcc-7. If you are using c++17 which this compiles with you need at least gcc-8. Otherwise force it to to compile with c++11 which works with gcc-7. I haven't tested it with other versions of c++ yet.

**Comment by vincentlaucsb** [comment]
This should be fixed by #87
