### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [vincentlaucsb/csv-parser#8]
Would you like to [wrap any pointer variables](https://github.com/vincentlaucsb/csv-parser/blob/00f2d2bcddec438b482d94d96bac31e1ca421969/src/csv_reader.cpp#L591 "Update candidate: CSVReader::read_csv()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by vincentlaucsb** [comment]
Fixed in 8d4a98e1910b0f7eadaec519959c21bc5bc5766e
