### ISSUE TITLE
Build errors if #include "csv.hpp" placed after #include "windows.h" under MSYS2

### ISSUE THREAD

**Issue by andvalb** [vincentlaucsb/csv-parser#82]
Steps to reproduce: 
change main cmake file to include 

_if(MSYS OR MINGW)
add_definitions(-DUNICODE -D_UNICODE)
endif()_

change tests/cmakelist.txt to include:

_if(MSYS OR MINGW) 
target_compile_options( 
csv_test PRIVATE -municode                                                                                                                                                                      ) 
set(CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -municode")
endif()_ 

change single_include_test/my_header.hpp
Add #include <windows.h> before #include "csv.hpp"
run "cmake ../ -G "MSYS Makefiles"" from build directory (already created)
then make.

Without windows header before csv header all compiles success.
gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 9.2.0

**Comment by vincentlaucsb** [comment]
This is probably related to #96. The offending/conflict symbols have been renamed. Feel free to reopen if I'm wrong, but please include the compiler errors.
