### ISSUE TITLE
Add option to ignore quote character

### ISSUE THREAD

**Issue by bangusi** [vincentlaucsb/csv-parser#83]
It appears the quote character defaults to `'"' `which works in many cases but I have ran into situations
where the file has no quote character specified. In such cases when `'"'` is encountered the parser produces  incorrect results. It can even lead to program crash.

**Comment by vincentlaucsb** [comment]
What happens if you set the quote character to a random character?

```
CSVFormat format;
format.quote('#')
```

I know this fix is not ideal, but if it works then I could just allow setting nothing as the quote character.

**Comment by bangusi** [comment]
Using some random character  works and that is a workaround that I used.
Problem is you have to know that character does not appear in the file. .. trial and error
Also in my case I didn't discover this was a problem until the program kept producing wrong result and sometimes crashing. The file had double quote that was not terminating

**Comment by vincentlaucsb** [comment]
It is 100% my intention to make the quoting character optional.

Can you give me a sample file or snippet of a file that crashes the parser? I'm trying to see if there are ways to deal with this without the parser crashing.

**Comment by bangusi** [comment]
I can't get the actual data file since I don't own the data. 
But roughly it is like below. 

```
column1~column2~column3~column4
value1~value2~"somevalue3~value4
value1~value2~somevalue3~value4
value1~value2~somevalue3~value4
value1~value2~somevalue3~value4
value1~value2~somevalue3~value4
value1~value2~"somevalue3~value4
```

It is a large file with over 2 million rows and more than 170 columns.
There is a large number of rows between the first occurrence of the quote and the next. The program would sometime combine content from multiple rows into a single token .i.e. spanning new lines.

I hope that helps.

**Comment by vincentlaucsb** [comment]
I've added the ability to turn off quoting in 1.3.3
