### ISSUE TITLE
How read the first line with a file without header ?

### ISSUE THREAD

**Issue by sylm21** [vincentlaucsb/csv-parser#84]
How read the first line with a file without header ?

Is it possible to catch errors while reading the file?

Thank's in advance

Sylm,

**Comment by sylm21** [comment]
Hi,

For files without headers, I start by processing the column names and then I go on classically.

Sylm

**Comment by vincentlaucsb** [comment]
Hi sylm21, what type of "errors" are you trying to catch?

**Comment by bangusi** [comment]
@sylm21  
You read the first line like
CSVReader reader("your_file.csv");
CSVRow row;
reader.read_row(row); // first call will read the first row
