### ISSUE TITLE
Field containing only whitespace, with trimming

### ISSUE THREAD

**Issue by omezrich** [vincentlaucsb/csv-parser#85]
Expected, when a field contains only whitespace and "trim" is set on format, that it will behave like an empty field, i.e. "1,,2".

However in this case parsing of the row seems incorrect. See attached test case for an example of failure.

    TEST_CASE("Test trim empty field") {
      CSVFormat format;
      format.column_names({ "A", "B", "C" })
            .trim({' '});
    
      std::stringstream csv_string;
      csv_string << "1, two,3" << std::endl
          << "4, ,5" << std::endl
          << "6,7,8 " << std::endl;

      auto rows = parse(csv_string.str(), format);
      CSVRow row;
      rows.read_row(row);

      // First Row
      REQUIRE(row[0].get<uint32_t>() == 1);
      REQUIRE(row[1].get<std::string>() == "two");
      REQUIRE(row[2].get<uint32_t>() == 3);

      // Second Row
      rows.read_row(row);

      REQUIRE(row[0].get<uint32_t>() == 4);
      REQUIRE(row[1].is_null());
      REQUIRE(row[2].get<uint32_t>() == 5);

      // Third Row
      rows.read_row(row);
      REQUIRE(row[0].get<uint32_t>() == 6);
      REQUIRE(row[1].get<uint32_t>() == 7);
      REQUIRE(row[2].get<uint32_t>() == 8);
    }

**Comment by vincentlaucsb** [comment]
Thanks for your report. I'll take a look.

**Comment by vincentlaucsb** [comment]
Thanks for contributing that test case. I've added a modified version of that in the final test suite.

This bug should be fixed by the latest release.

**Comment by omezrich** [comment]
Thank you!
