### ISSUE TITLE
Please consider to make "CSVField::get()" const.

### ISSUE THREAD

**Issue by toge** [vincentlaucsb/csv-parser#86]
I think "CSVField::get()" is almost const member function.
Please consider to make it const.

I want to write following code:
```
    for (const auto& row : rows) {
        for (const auto& field: row) {
            field.get<std::string_view>();
        }
    }
```

**Comment by vincentlaucsb** [comment]
Hi, I couldn't implement this exactly as asked because there are certain get<> templates which are not const.

However, if you just need a string_view, then the latest version adds `field.get_sv()` which is a `const` method.
