### ISSUE TITLE
Misparsing csv

### ISSUE THREAD

**Issue by OzanCansel** [vincentlaucsb/csv-parser#92]
Hi, 
Firstly i want to thank you for developing this library. Its usage is really elegant and easy.

Unfortunately, i faced with an issue which csv-parser parses the csv file wrongly. It parses fields wrongly. Am i missing something or is it a bug ? ( I generated .csv file from GNU Octave, i think its format is correct)

**Scenario to reproduce the issue:**
I have a csv file which contains 16384 columns and two rows. First row is an header, second row contains floating point values. .csv file is delimited by ','. (.csv file attaced as .zip)

```
#include <csv.hpp>

int main(int argc, char *argv[])
{
    using namespace csv;
    CSVReader reader("time-result.csv");

    for (CSVRow& row: reader) { // Input iterator
        auto i = 0;
        for (CSVField& field: row) {
            if ( i == 7003 ) // 7003th is one of the wrongly parsed fields, there are more
                std::cout << field.get<>() << std::endl;
            ++i;
        }
    }
}
```
**Output :**
`e-069.99`

But it should be a valid floating point numerical value string.

**Library Version** : 1.3.0
**Compiler** : gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

[time-result.zip](https://github.com/vincentlaucsb/csv-parser/files/4557089/time-result.zip)

**Comment by vincentlaucsb** [comment]
Ozan,

I appreciate your thanks. Currently, this library does not automatically convert floating point numbers written in exponential form.

However, if you use `get<float>`, `get<double>` and so on, you should the correct floating point value. From there, I believe there should be functions in the standard library that will convert it to a string. Let me know how that works for you.

See: https://github.com/vincentlaucsb/csv-parser#numeric-conversions

**Comment by OzanCansel** [comment]
Tried with `get<float>`, `get<double>` but it throws an error.

I haven't dig into the code but I think that there is a parsing issue. It somehow seperate fields wrongly by ',' seperator for these types.

Also another interesting thing, if i try to parse same .csv file as **16384x1** instead of **1x16384**(as transposed) it works.

```
#include <csv.hpp>

int main(int argc, char *argv[])
{
    using namespace csv;
    CSVReader reader("time-result.csv");

    for (CSVRow& row: reader) { // Input iterator
        auto i = 0;
        for (CSVField& field: row) {
            std::cout << field.get<float>() << std::endl;
            ++i;
        }
    }
}
```

> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Not a number.

**Comment by vincentlaucsb** [comment]
Do you mind posting a snippet of the CSV?

**Comment by OzanCansel** [comment]
> terminate called after throwing an instance of 'std::runtime_error'
> what(): Not a number.

This error was happened when I executed the snippet located in my previous post, which uses the **time-result.csv** I shared earlier. For clarification im attaching again.
[time-result.zip](https://github.com/vincentlaucsb/csv-parser/files/4570907/time-result.zip)

**Comment by vincentlaucsb** [comment]
Just wanted to know that I'm still looking at this. I rewrote your program slightly to just print all the numbers, and it looks like the parser starts misbehaving at i = 7000.

Looking further into it...

**Comment by vincentlaucsb** [comment]
![image](https://user-images.githubusercontent.com/18455475/81465316-0ee4bd80-917e-11ea-8433-637bf280abaf.png)

A bit of background here: this CSV parser goes through an input string and stores it in a data structure consisting of:
 * A string buffer (`std::string`) with text values (no delimiters, whitespace, etc.)
 * An array of indices (respective to the string buffer) of where each new field begins

I could have sworn I changed the index type to `size_t` (unsigned 64-bit int on Windows), but I still see `unsigned short` in my codebase (d'oh) and the the 7000th field occurs about 72000 characters in row 1. I think this is basically just an overflow error.

**Comment by vincentlaucsb** [comment]
> Also another interesting thing, if i try to parse same .csv file as 16384x1 instead of 1x16384(as transposed) it works.

Another thing, the overflow hypothesis is consistent with that observation

**Comment by OzanCansel** [comment]
So this overflow error constraints the row to contain 72.000 ( which is close to the limit of `unsigned short`) characters at maximum. That's why i get wrong values. It makes sense. Thank you for examining the issue :)

**Comment by OzanCansel** [comment]
Just an suggestion, maybe it is better to a add test which parses very long rows ( such as a row contains 100.000 columns ) to address this issue.

**Comment by vincentlaucsb** [comment]
This isn't the first time long rows have caused me issues so I will take that suggestion.

I'm stepping through the debugger and it seems like the number of columns is being counted correctly, further reinforcing my hypothesis it's just something wrong with that array of indices.

**Comment by vincentlaucsb** [comment]
![Found Bug](https://user-images.githubusercontent.com/18455475/81482728-0c21b100-91ee-11ea-80e0-efe519bc37cb.png)

I'm inspecting the array of indices. The index for the 7000th column is stored in position 23383 of the array because the array also contains the indices for the header row (16383 + 7000). This is an optimization to avoid allocating a new vector for each row, and makes sense for most CSVs (which have less than 500 columns).

However, as you can see we're getting some sort of overflow error.

![image](https://user-images.githubusercontent.com/18455475/81482788-70447500-91ee-11ea-9134-dc99db5c88f2.png)

Update: So that's why I couldn't find any warnings related to casting...

**Comment by vincentlaucsb** [comment]
Fixed in the latest release. Thanks for your report!

On another note, this might be the dumbest bug I've personally created due to overflow issues.
